openapi: 3.0.3
info:
  title: R&M Api
  description: thecatapi.com
  version: 1.0.0
servers:
- url: https://rickandmortyapi.com/api
tags:
- name: R&M Characters
paths:
  /character:
    get:
      tags:
      - R&M Characters
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: number
      - name: id
        description: The id of the character
        in: query
        required: false
        schema:
          type: number
      - name: name
        in: query
        description: The name of the character.
        required: false
        schema:
          type: string
      - name: status
        in: query
        description: The status of the character ('Alive', 'Dead' or 'unknown').
        required: false
        schema:
          type: string
      - name: species
        in: query
        description: The species of the character.
        required: false
        schema:
          type: string
      - name: type
        in: query
        description: The type or subspecies of the character.
        required: false
        schema:
          type: string
      - name: gender
        in: query
        description: The gender of the character ('Female', 'Male', 'Genderless' or 'unknown').
        required: false
        schema:
          type: string
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RMHeroesList'
        default:
          description: enexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
components:
  schemas:
    RMHeroesList:
      required:
        - "info"
        - "results"
      properties:
        info:
          type: "object"
          required:
          - "count"
          - "pages"
          - "next"
          - "prev"
          properties:
            count:
              type: "number"
            pages:
              type: "number"
            next:
              type: "string"
            prev:
              type: "string"
        results:
          type: "array"
          items:
            $ref: '#/components/schemas/Characters'
    Characters:
      type: "object"
      properties:
        id:
          type: "number"
        name:
          type: "string"
        status:
          type: "string"
        species:
          type: "string"
        type:
          type: "string"
        gender:
          type: "string"
        origin:
          required:
            - "name"
            - "url"
          type: "object"
          properties:
            name:
              type: "string"
            url:
              type: "string"
        location:
          required:
            - "name"
            - "url"
          type: "object"
          properties:
            name:
              type: "string"
            url:
              type: "string"
        image:
          type: "string"
        episode:
          type: "array"
          items:
            type: "string"
        url:
          type: "string"
        created:
          type: "string"
   
    ErrorModel:
      required:
      - code
      - message
      type: object
      properties:
        message:
          type: string
        code:
          maximum: 600
          minimum: 100
          type: integer
